# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imglink', models.CharField(default='null', max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField(max_length=700)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_upto', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(default='null', max_length=50)),
                ('category', models.CharField(default='null', max_length=50)),
                ('Deal', models.CharField(default='null', max_length=700)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
